### ISSUE TITLE
[Icon request] Choqok

### ISSUE THREAD

**Issue by ilpianista** [NitruxSA/plasma-next-icons#108]
Hi there,
would be possible to get an icon for Choqok too?

Current icon is https://projects.kde.org/projects/extragear/network/choqok/repository/revisions/master/entry/icons/hi128-app-choqok.png

I suppose https://bugs.kde.org/show_bug.cgi?id=344075 is a requirement for this, I'll take a look at that ASAP.

**Comment by DarkknightAK** [comment]
done by ken
