### ISSUE TITLE
Icon request for KDots

### ISSUE THREAD

**Issue by Ignotus** [NitruxSA/plasma-next-icons#112]
Hello,

I'm developing the game called KDots ( http://quickgit.kde.org/?p=kdots.git ) based on KDELibs . You can see its screenshots here https://github.com/Ignotus/kdots . Recently I have made a port to KF5 and I'm going to push it to the KDE Games project in the prospect. Unfortunately, it doesn't have its own icon currently.

Could you please create one icon (if it's possible)?

Regards,

Minh

**Comment by DarkknightAK** [comment]
was done

**Comment by Ignotus** [comment]
You cannot have such kind of polygon borders in the game of dots :) . Polygon is made when opponent's points are captured by the player and should be around the opponent's point. For instance:

![https://raw.githubusercontent.com/Ignotus/kdots/master/pictures/64-apps-kdots.png](https://raw.githubusercontent.com/Ignotus/kdots/master/pictures/64-apps-kdots.png)

Is it possible to change the icon a bit?

**Comment by DarkknightAK** [comment]
will check.

**Comment by DarkknightAK** [comment]
updated kdots does it work now?

**Comment by Ignotus** [comment]
it's very nice, thank you!
