### ISSUE TITLE
[Icon request] Kopete and Cantata icons

### ISSUE THREAD

**Issue by sergioad** [NitruxSA/plasma-next-icons#116]
Hello @UriHerrera and all the Nitrux team behind this awesome icon theme, A Breeze icon is needed for Kopete (the old but not because that dead KDE IM client) and for ou   Cantata (the KDE's MPD client) wich it's icon is obviouslly inspired by Oxygen (it looks like the Oxygen's blayback controls icons), both are very used on many KDE distros and Kopete is used by default in some distros like Arch (KDE extras meta package) OpenMandriva and many more

**Comment by UriHerrera** [comment]
Kopete is not only *old* according to Wikipedia the last _stable_ release was 2 years ago. So it may very well be discontinued or deprecated. Telepathy KDE on the other hand is supported and it has been ported to KF5.

In any case however make separate issues.

**Comment by sergioad** [comment]
Ok :smile:
