### ISSUE TITLE
New icon request: database key

### ISSUE THREAD

**Issue by staniek** [NitruxSA/plasma-next-icons#118]
A key metaphor is used for example in the context of database keys (https://en.wikipedia.org/wiki/Unique_key). (no, it's not about security)

Pretty good example from firefox (thought it means different thing):
![](http://i.imgur.com/K1Gm8at.png)

It is used in Kexi also as a small icon with text to indicate it's a name of such a key. The current icon comes from the oxygen times:

![](http://i.imgur.com/lZRhaAe.png)

Similar thing for MS Access:

![](https://support.microsoft.com/library/images/2878329.png)

Proposed name: database-key

**Comment by staniek** [comment]
Idea: there's a key already in the *lc_starchartdialog.svg* icon, could be reused maybe?

**Comment by DarkknightAK** [comment]
one moment you get one in a view minutes. I only have to setup the git repository. now I work in the LO git and when I'm finished there the svg files from LO will be here. so one minute.

**Comment by staniek** [comment]
See also my request other #119.

**Comment by staniek** [comment]
@DarkknightAK Reaction in 2 minutes??? You rock!

**Comment by DarkknightAK** [comment]
I'm not sure if it work. I would say make a request for kexi breeze icons than we can make an full icon set.

**Comment by staniek** [comment]
Looks cool. I'll make requests, one by one.
