### ISSUE TITLE
New icon request: database index

### ISSUE THREAD

**Issue by staniek** [NitruxSA/plasma-next-icons#119]
A small thunder metaphor tends to be used for example in the context of database indices (https://en.wikipedia.org/wiki/Database_index).

See the top-left icon from MS access:
![](http://www.functionx.com/access/windows/indexes1.gif)

I am aware of existence of the *lc_starchartdialog.svg* icon ![](http://i.imgur.com/E8vF2P2.png) but I find it overlapping with the database key icon (see also my request #118).

The icon will be used in Kexi also as a small icon with text to indicate it's a name/field with an index.

Proposed name: database-index

**Comment by UriHerrera** [comment]
There's `quickopen-file` and `quickopen-class` which are similar. Maybe just a link to any of those.

**Comment by staniek** [comment]
@UriHerrera Thanks for this good find! I think that the index icon is far more specific than the db key icon, so I think I can grab the quickopen icon and adapt internally in Kexi. Especially that I'll need a sharp 16px version too.

**Comment by DarkknightAK** [comment]
Hi @staniek 16 px toolbar support was finished yesterday so you also have the quickopen-file and quickopen-class icon in 16 px.

**Comment by staniek** [comment]
Thanks @DarkknightAK 
Regarding this

 ![database-index.svg](http://i.imgur.com/FflEpcL.png)
database-index

Isn't there a conflict with the pkey.svg? As I said at the top 'I find it overlapping with the database key icon'

 ![pkey](http://i.imgur.com/aKPxWTW.png)
pkey

If someone uses the icons, most typically both are used in the same UI.

**Comment by DarkknightAK** [comment]
the pkey is from the LibreOffice folder or?

**Comment by DarkknightAK** [comment]
the pkey icon is special for LO and it is only 11x11 px in height. you can also have an vertical key if you like.
Please do not use ANY icons from the LibreOffice icon set in your application, because this folder is not part of kde:breeze.

**Comment by staniek** [comment]
Sure I won't. Just referring to the fact that that in the database domain both 'key' and 'index' are terms that need icons. If 'index' takes the 'key' metaphor, what will be key's metaphor?

**Comment by staniek** [comment]
Some competing tools use the same icon for index and key just with different colours, e.g. gray/gold:
![](https://www.devart.com/dbforge/oracle/studio/images/highlights/screenshot-query-builder-01.png)

I don't know it this is compatible our 'language'.

This is what the popular phpMysqlAdmin tool uses:

![](http://i.imgur.com/xHGpLVf.png)

![](http://i.imgur.com/7QqQsRT.png)

**Comment by DarkknightAK** [comment]
ah ok that's my fault. In LO I use for key the gray key and for primary key an blue key.

there is gtk-index which is used from LO (document) index. It is more from documents, should it work for database index too?

https://github.com/NitruxSA/plasma-next-icons/blob/master/Breeze/actions/toolbar-gtk/gtk-index.svg

**Comment by staniek** [comment]
@DarkknightAK the smallest the better, having a design that fits in 11x11 is nice. 
The gtk-index is detailed, when simplified it could be list view-list-text. Could we try a thunder for it because as I mentioned:
>If you need hints on semantics, the index refers to "add a speed up, optimize" the information lookup > from the database.

**Comment by DarkknightAK** [comment]
there is also an small size gtk-index file 
https://github.com/NitruxSA/plasma-next-icons/blob/master/Breeze/actions/toolbar-small-gtk/gtk-index.svg
but if you like the thunder, you get an thunder.

**Comment by DarkknightAK** [comment]
please give me feedback if the icon would work for you. I can also offer an smaller one but before I have to change the folder names and this is something after 5.4.

**Comment by staniek** [comment]
@DarkknightAK The thunder is awesome, thanks!
