### ISSUE TITLE
[Icon request] Calligra icons

### ISSUE THREAD

**Issue by sergioad** [NitruxSA/plasma-next-icons#122]
Hello @UriHerrera and all the people behind the Breeze icons (wich are awesome) I am here to ask you for the Calligra suit wich is the succesor of KOffice, like Cantata these apps are not "directly" themed by Oxygen but it's icons have all the oxygen artwork style so all of them should be themed as soon as possible, the icons used by the suite are horrible (or at least some of them), a refresh of it's style is needed for making it more eyecandy and modern

**Comment by UriHerrera** [comment]
The Calligra suite has app icons and it already uses Breeze icons.

**Comment by sergioad** [comment]
Ok :smile:

**Comment by DarkknightAK** [comment]
@UriHerrera we remove the calligra icons because they doesn't fit.

**Comment by DarkknightAK** [comment]
ken make the calligra icons again and he is in response with the calligra devs. hope they like the new ones.

**Comment by DarkknightAK** [comment]
ken updates the icons and change them according to the dev's recommandations. so I think this issue can be closed.
