### ISSUE TITLE
Move Libreoffice icons out of freedesktop space

### ISSUE THREAD

**Issue by jriddell** [NitruxSA/plasma-next-icons#124]
Libreoffice icons are in actions/LO_icons_breeze/ and actions/LO_lc_icons_breeze/

This means they get installed along with all the rest which wastes disk space and breaks gtk-icon-cache because of names it doesn't like.

Please move these directories up a directory so they don't get installed.

**Comment by DarkknightAK** [comment]
I had the same idea yesterday :-)
