### ISSUE TITLE
breeze-dark: wrong Inherits in index.theme causes fallback to hicolor

### ISSUE THREAD

**Issue by Soukyuu** [NitruxSA/plasma-next-icons#127]
I've just updated to breeze 5.2.95 and breeze-dark filetype icons seem to fallback to hicolor

This is probably because you have
```
Inherits=Breeze
```
in your index.theme, while the directory is named `breeze`. Case sensitivity throws it off. 
Changing the above to `Inherits=breeze` works.

**Comment by UriHerrera** [comment]
The folder *is* called Breeze (with the uppercase B) I'm assuming packagers are changing it to a lowercase b.

**Comment by Soukyuu** [comment]
You are right, I did check the index.theme but didn't see the uppercase B in your repository. Considering the arch linux packagers told me [they didn't change anything](https://bugs.archlinux.org/task/44592), I guess it's an error on KDE packaging side.
