### ISSUE TITLE
[Request] set with monochrome style icons

### ISSUE THREAD

**Issue by sl1pkn07** [NitruxSA/plasma-next-icons#130]
Hi

is possible add a set of all icons in monochrome style?, i mean all icons like the bottom of the screenshot (https://camo.githubusercontent.com/5b38b1b490f61abfeda76e026c7f598a9bfcf8e9/687474703a2f2f692e696d6775722e636f6d2f6f6d45523256542e706e67).

greetings

**Comment by DarkknightAK** [comment]
Hi

in the wiki you have all used colors for monochrome icons (https://github.com/NitruxSA/plasma-next-icons/wiki/Icon-design-guidelines-in-Breeze)

when you download the icon set you can search the svg files after the color plate colors and change them. as svg is a text file this is no problem.

e.o.: sed s/da4453/4d4d4d/g filename.svg
change the red element from the monochrome icons into gray

**Comment by sl1pkn07** [comment]
mmm then the "monochrome" is not a style i wanted,

I what keep a color icons if have only one main color (or if have less other color details)

for example, i whant transform the folder icon like 

user-folders/folder-magenta.svg

to

user-folders-small/folder-magenta.svg

but with keeping the size

this in all "full color" icons (like apps/software/system-file-manager.svg, mimetypes/file-types/inode-directory.svg, etc)

greetings

**Comment by DarkknightAK** [comment]
Then you have to use another icon set. Sorry.
