### ISSUE TITLE
[Icon request] LibreOffice dark icons

### ISSUE THREAD

**Issue by aitorpazos** [NitruxSA/plasma-next-icons#138]
Building a package to make Breeze icons for LibreOffice available in ArchLinux (https://github.com/aitorpazos/archlinux-libreoffice-breeze-icons/blob/master/libreoffice-breeze-icons-src/Makefile), I used Imagemagic (replacing #4d4d4d with #f2f2f2) to build LO dark theme icons. This is just a workaround to make this theme usable with dark themes, but it would be great to have a LibreOffice_Breeze/breeze_dark folder with the proper set of icons.

**Comment by DarkknightAK** [comment]
hi

at the Moment LO don't include a dark theme. also for sifr there is only a light theme. the idea was that LO support color changing. you also have to change a second color light gray. will send you the number later.

**Comment by aitorpazos** [comment]
Ok thanks, is it: #adadad -> #f9f9f9 ? I've added this mapping as well.
I don't understand this statement very well: "at the Moment LO don't include a dark theme.", If a user selects a dark GTK theme for his desktop, LO will use it and light icons won't work well...

**Comment by fitojb** [comment]
> I don't understand this statement very well: "at the Moment LO don't include a dark theme.", If a user selects a dark GTK theme for his desktop, LO will use it and light icons won't work well...

That doesn’t have anything to do with LibreOffice including an *icon theme* for dark *GTK themes*.

**Comment by DarkknightAK** [comment]
I thought that you need the zip file for the LO icons, don't know that LO also use the icons from the GTK theme. So when someone can help me with the KDE/GTK theme than no problem.

**Comment by aitorpazos** [comment]
I think we are getting confused. AFAIK, LO doesn't use GTK theme's icons (it uses its own sets of icons), but if user's desktop colors are dark (KDE or GTK desktop configuration), LO use these colors for it's interface and "/LibreOffice_Breeze/breeze" icons are hard to see. That's why I think we should provide "LibreOffice_Breeze/breeze_dark" as we do with "/Breeze" and "/Breeze Dark" sets.
![lo_dark](https://cloud.githubusercontent.com/assets/2015196/7559922/e01dd5b8-f7bd-11e4-9b6d-7e9f6162a8b7.png)
![lo_light](https://cloud.githubusercontent.com/assets/2015196/7559923/e02438f4-f7bd-11e4-81c5-77b040264016.png)

**Comment by DarkknightAK** [comment]
that's also my knowlege. the thing is should LO support breeze-dark and sifr-dark in additional or is it possible to make the dark theme with code (text file with light and dark color). I'd prefere to support an additional icon theme now and in future maybe codebased. You don't have to ship the dark themes for e.o. windows. Kubuntu ship only breeze for example.

**Comment by aitorpazos** [comment]
I've checked Kubuntu and it suffers from the same problem, they haven't fixed it. I understand that it's much more maintainable to keep just one tree of icons, but at the same time, as upstream, we should provide some solution to this issue. I'm creating a pull request with a Makefile to create both icon themes. The dark theme is created on the fly replacing SVG colors #4d4d4d and #adadad with #f2f2f2 and #f9f9f9, respectively.
![snapshot_kubuntu](https://cloud.githubusercontent.com/assets/2015196/7571037/1a8e7a66-f815-11e4-9998-5c6d680abd49.png)
