### ISSUE TITLE
[Icon request] Kamoso icons

### ISSUE THREAD

**Issue by aleixpol** [NitruxSA/plasma-next-icons#140]
Needed icons:
* Kamoso (photobooth-like software) application icon
* Shoot action button (currently the same as the app, but not necessary)
* Burst action button.

https://forum.kde.org/viewtopic.php?f=285&t=125873

**Comment by DarkknightAK** [comment]
I think we are finished with Kamoso. sorry for the long waiting time but we hope you are happy with the result and we can work also in future together. ping us at the VDG forum.

**Comment by aleixpol** [comment]
No problem, I'm happy about the new artwork, thank you very much!
