### ISSUE TITLE
[Icon request] dialog-question icon

### ISSUE THREAD

**Issue by benedictleejh** [NitruxSA/plasma-next-icons#147]
Hi, I'm using Intellij IDEA (it's Java Swing based, and therefore uses GTK), and when the confirm close dialog pops up, because of the lack of a `dialog-question` icon in both Breeze and Oxygen (my fallback icon set), another icon which doesn't quite fit is used instead. I currently workaround this by symlinking `dialog-information` to `dialog-question`, but it would be nice to get a proper icon for question dialogs. A symlink shipped with the icon set would be nice too, so we won't have to do it ourselves.

Thanks.

**Comment by DarkknightAK** [comment]
was done.
