### ISSUE TITLE
[Icon request] Firefox menubar icons

### ISSUE THREAD

**Issue by benedictleejh** [NitruxSA/plasma-next-icons#148]
Hi, I'd like to request icons for the items inside Firefox's menubar menus.

The icons currently not covered by Breeze are:

```
File > New Tab
       New Window
Edit > Preferences
History > Show All History
Bookmarks > Show All Bookmarks
            Bookmarks Toolbar
            Recently Bookmarked
            Recent Tags
Tools > Downloads
        Add-ons
```

A couple of them could possibly be covered by simply symlinking (or setting the right icon mapping) appropriate looking existing icons to the right names (e.g. Preferences, Downloads).

Thank you.

**Comment by DarkknightAK** [comment]
It would be really helpful when you can write the icon names to.

**Comment by benedictleejh** [comment]
I really wish I could give you the icon names, but I've been searching throughout my system, and I can't find them at all. The icons must be somewhere on the system, but I can't find them. The Firefox source isn't particularly enlightening either. To complicate matters, the icons appear on Linux, but not on Windows, which leads me to think they might be GTK icons, but they don't appear where my default GTK icons are.

**Comment by DarkknightAK** [comment]
we added also gtk toolbar icons and a lot of the gtk specific icons used by firefox were now breeze icons. BUT the most firefox icons (the monochrome ones) are from the firefox source and CAN'T be changed. So we did as much as we can to have the breeze experience also in firefox.
