### ISSUE TITLE
Missing floppy icon

### ISSUE THREAD

**Issue by benedictleejh** [NitruxSA/plasma-next-icons#149]
When using a GTK save dialog, the floppy icon for the dialog uses the GTK icon. Since Breeze already has a floppy icon in the save icon, perhaps that could be reused?

Thank you.

**Comment by UriHerrera** [comment]
GTK software should be using the icon with the standard name of _document-save_. If it doesn't use that icon then that should be patched in the software.

GTK 3 software uses (mostly) or should be using symbolic icons, which we do not provide.

**Comment by benedictleejh** [comment]
Hi, I'm not talking about the save icon directly. In a GTK save dialog, in the list of places, there is a floppy disk location. That location currently uses the GTK floppy icon. I believe that icon is named _media-floppy_, which Breeze currently does not have one.

**Comment by UriHerrera** [comment]
Can you add a screenshot?.

**Comment by benedictleejh** [comment]
Here's a screenshot:

![GTK save dialog screenshot](http://i58.tinypic.com/xojwar.jpg)

**Comment by DarkknightAK** [comment]
#benedictleejh does it work for you?

**Comment by benedictleejh** [comment]
That works great. Thanks.
