### ISSUE TITLE
Kontact icons missing

### ISSUE THREAD

**Issue by m1ga** [NitruxSA/plasma-next-icons#156]
some icons in Kontact don't look right (old?) in the current Fedora 22 - KDE:
![screen](http://www.migaweb.de/screen.jpg)

* Kontact icon (taskbar, window icon)
* contact icon
* calendar icon
* akregator icon
* little envelop icons in the email list

**Comment by UriHerrera** [comment]
Indeed though it would be great if you could provide the name of the icons.

**Comment by m1ga** [comment]
Whats the quickest way to find them?

**Comment by Steinhagen** [comment]
Kontact icon name: 'kontact'
/usr/share/icons/hicolor/128x128/apps/kontact.png

Contact (Kaddressbook) icon name: 'kaddressbook'
/usr/share/icons/hicolor/64x64/apps/kaddressbook.png

Calendar (Korganizer): 'korganizer'
/usr/share/icons/hicolor/128x128/apps/korganizer.png

Akregator icon name: 'akregator'
/usr/share/icons/hicolor/128x128/apps/akregator.png

**Comment by DarkknightAK** [comment]
app icons:
- akregator
- kjournal
- knotes
- kontact-import-wizard
- kontact

**Comment by m1ga** [comment]
:+1: thanks

**Comment by KAMiKAZOW** [comment]
You can close this. #203 has been merged.

**Comment by DarkknightAK** [comment]
some app icons (kjournal) are still missing, but it is on my radar. thanks for your feedback
