### ISSUE TITLE
Add icon for missing album art

### ISSUE THREAD

**Issue by Sogatori** [NitruxSA/plasma-next-icons#16]
Heya Uri,

the Plasma people have asked if we could provide an icon to display when there's no album coverart availalbe. Currently they use this:
![Current CoverDummy](http://quickgit.kde.org/?p=plasma-mediacenter.git&a=blob&h=54aee6d5a04090861305c950d790e88847ce5d4a&f=images%2Fhi192-status-pmcnocover.png&o=plain)
It will be used in the system tray media control applet and PMC.

**Comment by Sogatori** [comment]
I thought they could just reuse the icon in both programms. At least that was the plan as far as I know.

**Comment by UriHerrera** [comment]
System tray icons are 22 px (with the *rare* exception of plasma-nm which uses a 28 px icon for *some reason*).

What size do they need for the larger icon?.

**Comment by Sogatori** [comment]
Oh, I think I miscommunicated here. It's not an system tray icon. Plasma 5 has a system tray item, that is active when a media player is … well playing. When one clicks on item a popup opens with media controls. And the cover is shown in said popup the cover art icon will be needed.

![example](http://wstaw.org/m/2015/01/06/mediaalbumart.png)
Notice there is already an icon for the system tray ^_^

The icon should be 128X128. But they said tit does not really matter any way, as long as it is an .svg.

**Comment by UriHerrera** [comment]
Where's the icon located?, and name should it have?.

**Comment by UriHerrera** [comment]
I added this icon to the folder */plasmoids*

![icon](http://i.imgur.com/VQHaDgM.png)

**Comment by UriHerrera** [comment]
Well it's now on /plasmoids :) - I'll rename it then.
