### ISSUE TITLE
Low quality input sources flags

### ISSUE THREAD

**Issue by Steinhagen** [NitruxSA/plasma-next-icons#163]
The flags used for the input sources either don't have the correct aspect ratio, either they are pixelated.
The flags of Romania and France should have the same aspect ratio (2:3):
![flags](https://cloud.githubusercontent.com/assets/4029937/8019435/3f1fb962-0c56-11e5-8514-eb7abcd6982b.png)
You can literally count the pixels of the Nepal's flag:
![pixelated](https://cloud.githubusercontent.com/assets/4029937/8019436/40ae0c66-0c56-11e5-9460-abbffaa498a3.png)

**Comment by DarkknightAK** [comment]
what't the name of the app and do you know the icon names?

**Comment by Steinhagen** [comment]
Unfortunately, I don't know exactly the program or what are the icons names, reason why I was reluctant to rise this ticket...

**Comment by UriHerrera** [comment]
These flags are not part of the Oxygen icons either so we'll consider them not canonical to Breeze. They're also not part of the FreeDesktop icon standards, so they're not by that means in any other icon themes out there. Those then are assets provided by the software that uses them and its developers.
