### ISSUE TITLE
SMPlayer icon and icon theme

### ISSUE THREAD

**Issue by rthomsen** [NitruxSA/plasma-next-icons#167]
Any chance we can get a SMPlayer icon? The default one looks hopelessly out of place in Breeze.

Also a Breeze icon theme for SMPlayer would be really nice....

**Comment by rthomsen** [comment]
I found this forum thread: https://forum.kde.org/viewtopic.php?f=285&t=123210
which indicates some work is/was ongoing on a Breeze icon theme for SMPlayer, but there is no download link.

**Comment by DarkknightAK** [comment]
Done see https://forum.kde.org/viewtopic.php?f=285&t=123210&p=336569#p336569

**Comment by rthomsen** [comment]
@DarkknightAK Thank you very much for the nice icon theme! :+1: Now only a Breeze icon for SMPlayer is missing :)

**Comment by DarkknightAK** [comment]
@rthomsen thanks. I post the theme in the SMPlayer forum and we will see what they want. http://forum.smplayer.info/viewtopic.php?f=7&t=8050&sid=18639f6406e14b15e34d4547545bdf5a

I'm not that good in app icons but we will see. Also app icons should be discussed with the app developers I think. And for me it is no problem to have the original app icons and the overall theme is in each kde/plasma app the same.

**Comment by DarkknightAK** [comment]
new breeze icons will come to the next smplayer release

**Comment by rthomsen** [comment]
Great news, and I saw an smplayer icon was also pushed to the breeze repository. Guess it will be released as part of Plasma 5.4. Thanks very much for your fine work :) Closing the issue...
