### ISSUE TITLE
Konversation icon looks pixelated when using "Large Icons" task switcher

### ISSUE THREAD

**Issue by rthomsen** [NitruxSA/plasma-next-icons#168]
Compared to other icons, the konversation icon looks very pixelated when using the "Large Icons" task switcher in KDE (see screenshot).

![konv1](https://cloud.githubusercontent.com/assets/4071934/8103719/dc7d6a24-102a-11e5-9490-39710170c147.png)

**Comment by UriHerrera** [comment]
I don't think I had that problem before but anyways I made a screenshot: 

![](http://i.imgur.com/cEuutzl.png)

I just made a commit and the icon isn't pixelated.

**Comment by rthomsen** [comment]
Hmm, the icon looks really nice in your screenshot. I don't know why it would be pixelated on my system. I checked and I have the latest version of the icon.

**Comment by DarkknightAK** [comment]
A new konversation icon was added. ALL or icons are svg files. please check the git clone again, because your bug is not repeatable

**Comment by rthomsen** [comment]
I tried the icons from a recent git snapshot. Strangely, the new konversation icon is also pixelated:
![icons-taskswitcher](https://cloud.githubusercontent.com/assets/4071934/8983416/73d00ce0-36ca-11e5-8e2b-822d440387c2.png)

I noticed that the ksnapshot icon is also pixelated (unfortunately, it removes itself from the task switcher when taking the snapshot). I tried displaying the icon in large size in Dolphin:
![icons-dolphin](https://cloud.githubusercontent.com/assets/4071934/8983458/bca2b54e-36ca-11e5-8f7e-2ba9d7b8b113.png)

Here they are not pixelated. So I guess the icons themselves are not to blame. I just don't understand why some icons would be pixelated while others are not (they are all SVG).

**Comment by rthomsen** [comment]
I just dicovered that konversation and ksnapshot don't set the window icon with the function:
`QApplication::setWindowIcon()`
in their main().

Adding this to the main() function fixes the pixelated icons for both apps, e.g. for konversation:
`app.setWindowIcon(QIcon::fromTheme(QStringLiteral("konversation")));`

**Comment by rthomsen** [comment]
This was already fixed in master branch of konversation and I just committed the fix to frameworks branch of ksnapshot:
http://quickgit.kde.org/?p=ksnapshot.git&a=commit&h=cf663ed1e0c03c57bf270179d8ff130610391389
