### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by debfx** [NitruxSA/plasma-next-icons#169]
README.md and LICENSE say the icons are licensed under the LGPLv3.

Some svg files however have metadata that says they are licensed under CC-BY-SA:
LibreOffice_Breeze/breeze/res/lx03167.svg
LibreOffice_Breeze/breeze/res/lx03166.svg
LibreOffice_Breeze/breeze/res/lx03164.svg
LibreOffice_Breeze/breeze/cmd/lc_save.svg
LibreOffice_Breeze/breeze/cmd/lc_cut.svg
Breeze/actions/toolbar/edit-cut.svg
Breeze/actions/toolbar/document-save.svg
Breeze/actions/toolbar/document-save-as.svg
Breeze/actions/toolbar/document-save-all.svg
Breeze Dark/actions/toolbar/edit-cut.svg
Breeze Dark/actions/toolbar/document-save.svg
Breeze Dark/actions/toolbar/document-save-as.svg
Breeze Dark/actions/toolbar/document-save-all.svg

Could you please clarify the license of these files?

**Comment by UriHerrera** [comment]
I removed the old license metadata.
