### ISSUE TITLE
Implement all freedesktop standard icons

### ISSUE THREAD

**Issue by flying-sheep** [NitruxSA/plasma-next-icons#197]
Overview here: http://flying-sheep.github.io/freedesktop-icons/

**Comment by UriHerrera** [comment]
Please note that: 
* The Freedesktop standard while the _standard_ it's far from having the icons Plasma needs and/or uses. This is mentioned here: https://github.com/NitruxSA/plasma-next-icons/wiki/Iconography-introduction-for-Breeze#background
* Please note that some of the icons *are not* used by Plasma but by GTK software. Some icons provided even by the Plasma theme itself and not the icon theme.
* Some icons do not follow the naming convention we use, see: https://github.com/NitruxSA/plasma-next-icons/wiki/Icon-naming-and-categorization-guidelines-in-Breeze

**Comment by flying-sheep** [comment]
ok, was just checking if that was an intention :smile:
