### ISSUE TITLE
Akregator tray icon inconsistent

### ISSUE THREAD

**Issue by KAMiKAZOW** [NitruxSA/plasma-next-icons#204]
See this screenshot (magnified):
![5](https://cloud.githubusercontent.com/assets/3259076/8947143/9f7c2038-3597-11e5-86c3-cc22189e8e4a.png)

The left icon is from this icon theme – it is used when Akregator displays the unread news counter.
The right one is from the Breeze Plasma theme – used when there are no unread news items.

CC: @Ken-Vermette

**Comment by DarkknightAK** [comment]
the left icon is from me. It's the same icon as for rss toolbar icons.
I see that there are differences between breeze icons and the icons from the plasma theme. As there are two different icons in two different repositories I would say both icons should come from plasma (or breeze-icon).
that's the problem when there are two different storage posibilities.

**Comment by KAMiKAZOW** [comment]
So, it's up to @Montel to always use the Plasma one for the tray?

**Comment by UriHerrera** [comment]
The plasma theme and the icon theme were not made by the same person and thus used different assets as you can tell from the icons (like your image) their color and their style. Only a couple, being both network icons (wired and wireless) are shared by both.

**Comment by KAMiKAZOW** [comment]
FYI: Montel Laurent is the one currently taking care of the KF5 port of the PIM apps.

**Comment by DarkknightAK** [comment]
yes please say @Montel to use ALLWAYS the plasma one. I also update the breeze-akregator icon so that it should work now too.
