### ISSUE TITLE
"user-desktop" icon looks fuzzy in "Show desktop" applet

### ISSUE THREAD

**Issue by s-kostyuk** [NitruxSA/plasma-next-icons#207]
Illustration:
![show desktop applet](https://cloud.githubusercontent.com/assets/5122578/8958185/ff5559d8-360b-11e5-9ebf-7f3fbeaa77d4.png)

**Comment by UriHerrera** [comment]
That icon is 16px. The system tray uses 22px icons that's why it's blurred.

**Comment by s-kostyuk** [comment]
Looks great! Many thanks
