### ISSUE TITLE
remove 16 and 22px monochrome app icons

### ISSUE THREAD

**Issue by DarkknightAK** [NitruxSA/plasma-next-icons#252]
Hi Uri,

a lot of users don't like the small app icon for dolphin and the terminal in the panel. you also write in the index.theme file that the small app icons are a workaround. can we find a better solution? 

what happens when system-file-manager and utilties-terminal (in 22px) will be removed?

**Comment by UriHerrera** [comment]
Not until whoever is maintaining Dolphin changes those icons to something else.

**Comment by Paviluf** [comment]
Why don't make the "big" icons for dolphin and the terminal smaller, at least for now ?

**Comment by UriHerrera** [comment]
Because I don't want to nurture bad use of icons and I don't want to break our own guidelines.

**Comment by Paviluf** [comment]
Ok so why not simply remove these icons if they will use the larger application icons ?

**Comment by DarkknightAK** [comment]
ok I'll start this discussion and so I have to say also what I'm thinking.

use the wrong icon (eo. app icon in an toolbar) is the worst thing what could happen. We now have an workaround that cause other problems (panel icon). There is only ONE final solution change the icon to the right one. And of course we have guidelines and when we don't observe them it would be better to delete the guidelines.

for the next release 5.5 there is enough time to solve this problem. I leave it in https://phabricator.kde.org/T583 but the message should be clear follow the guidelines and when an icon is missing leave a message.

**Comment by UriHerrera** [comment]
I'm going to close this because like I've said (by now) numerous times this isn't a problem of the icon theme, this is problem of the software pulling the wrong icon.
