### ISSUE TITLE
get-hot-new-stuff.svg from Breeze Dark

### ISSUE THREAD

**Issue by alltiptop** [NitruxSA/plasma-next-icons#36]
rating in amarok is invisible (all stars white), for fix changes color of get-hot-new-stuff.svg to yellow (#fdbc4b in other yellow breeze icons)
http://i.imgur.com/asfYLIh.png

**Comment by UriHerrera** [comment]
There's two star icons *rating* and *get-hot-new-stuff* it's likely (and I hope I'm right) that Amarok is using *rating* which it can be changed as long as no other software uses *rating* for other purposes.

**Comment by alltiptop** [comment]
maybe then change and unlink rating icon?

**Comment by UriHerrera** [comment]
Well yeah however using yellow according to the [guidelines](https://github.com/NitruxSA/plasma-next-icons/wiki/Icon-design-guidelines-in-Breeze) would mean warning. It'd actually be orange.

**Comment by alltiptop** [comment]
green

**Comment by UriHerrera** [comment]
I've edited the guidelines and added that the color `#fdbc4b` is used for that icon too. I'll update the icon in a minute.
