### ISSUE TITLE
Icon request: draw-line (and others)

### ISSUE THREAD

**Issue by callaa** [NitruxSA/plasma-next-icons#52]
Hello.
I'm writing a Qt based online drawing application and would like to request three new toolbar icons:

* Straight line tool (`draw-line`). This icon is included in Oxygen.
* Watercolor brush. In my app, this is a variation of the regular brush that picks up color from the layer. As far I know, there is no standard name for this one.
* A virtual laser pointer tool: this an online whiteboard tool for pointing at things on the canvas, like a real laser pointer. Not sure if there is a standard name suitable for this.

**Comment by callaa** [comment]
Here are my proposals for the draw-line and draw-watercolor icons: 
![new-draw-icons-preview](https://cloud.githubusercontent.com/assets/464576/6151216/0b3bd9ac-b21d-11e4-848f-aa7ed854f426.png)

The `draw-line` icon is basically the one from Oxygen redone in Breeze style.

The `draw-watercolor` is a combination of the brush and color picker icons, which I think reflects how the watercolor brush typically works.

I haven't come up with a custom icon for the laser pointer tool, but the current `cursor-arrow` seems like a suitable replacement.

I can open a pull request, if this is acceptable.

**Comment by UriHerrera** [comment]
Sure, open the pull request.

At the size the icons are I don't know if an actual laser icon would be recognizable enough, I'd have to try. But if the cursor icon works for you that's also cool.

**Comment by callaa** [comment]
Thanks.
The laser icon I'm using right now is a red dot, but that would not readily translate to Breeze style, because of the reservation of red color for destructive actions, and the laser pointer tool being about as non-destructive as it gets. The arrow cursor icon is a suitable substitute though, since the tool is basically just a cursor for pointing at things.
