### ISSUE TITLE
Reuse konversation.svg for more IRC clients

### ISSUE THREAD

**Issue by KAMiKAZOW** [NitruxSA/plasma-next-icons#61]
The current konversation.svg is generic enough to serve as icon for other IRC clients as well. Quassel and XChat come to mind.

**Comment by DarkknightAK** [comment]
there is an app icon for x-chat and quassel is the kde app so I prefere to have breeze icons for all kde apps. but it need time. you can read the wiki and make an draft for the missing app icons. uri is a really good teacher.

**Comment by KAMiKAZOW** [comment]
Just use the same icon. konversation.svg is a generic IRC icon.

**Comment by UriHerrera** [comment]
Icon requests are preferably 1 per issue and should be specific about what icons are needed.
