### ISSUE TITLE
Colored icons

### ISSUE THREAD

**Issue by horosgrisa** [NitruxSA/plasma-next-icons#67]
Please, add folder-magenta, folder-purple, and others.

**Comment by staniek** [comment]
Colorization can be made programatically. Please ask by posting a wish to bugs.kde.org or KDE forums. 

The colorization could be quite easy especially because we have mostly flat colors in Breeze (compared to Oxygen).

**Comment by DarkknightAK** [comment]
do you mean additional color folders? there is folder-violet in the repository. there are 9 colored folder icons when we add more the user can't recognize the differences.

**Comment by staniek** [comment]
If we had colorization we could remove the extra folders.

We will have to use colorization for dark/light Breeze anyway because (for example) selected UI items need negative colors.

**Comment by horosgrisa** [comment]
https://www.dropbox.com/sh/l3ptrkt1vuumoz6/AADlsBFsZqkJVarhBXQR9DRMa?dl=0

**Comment by DarkknightAK** [comment]
the icon looks good! make a pull request. there are only a few colors because in oxygen there are also only this few colors. in addition the colors have to be different enough. But again I like it and the style is like at the other icons. pull request.
