### ISSUE TITLE
[Icon request] select-lasso

### ISSUE THREAD

**Issue by callaa** [NitruxSA/plasma-next-icons#71]
I would like to request an icon for free-form (lasso) selection tool.

An example of this icon can be found in the [Tango ArtLibreSet](http://tango.freedesktop.org/ArtLibreSet).

**Comment by UriHerrera** [comment]
Please add the icon name of the file that you need too.

**Comment by callaa** [comment]
The icon name is `select-lasso` and the category is toolbar.

**Comment by UriHerrera** [comment]
I've added the icon as `edit-select-lasso` as that is a more standard name.

**Comment by callaa** [comment]
Thank you!
