### ISSUE TITLE
[Missing Icon] im-status/user-away-extended

### ISSUE THREAD

**Issue by mck182** [NitruxSA/plasma-next-icons#75]
Hey,

so in KDE Telepathy (and pretty much any KDE IM client) there's also presence known as "Not Available" or "Extended Away". Currently the KDE Telepathy client is using the Breeze icons for im status but the "Not Available" is missing and so it falls back to oxygen for this one, which feels strange (as oxygen icons are totally different). In oxygen, the icon name is "user-away-extended".

So I'd like to request this missing icon for Breeze. I'd suggest making some variant of "user-away", like darker or add some other feature to it.

Thank you

**Comment by DarkknightAK** [comment]
there is a user-idle icon in the breeze git repository but in my oxygen theme there wasn't an idle icon, maybe we can rename or link to the idle icon ![user-idle](https://dl.dropboxusercontent.com/u/1642456/vdg/plasma-next-icons/breeze/status/im-status/user-idle.svg)

**Comment by mck182** [comment]
Yeah, that would do I think.
